server:
  port: 8080
  servlet:
    contextPath: /management
spring:
  profiles:
    active: local
  application:
    name: superheroes
  flyway:
    enabled: true
    user: ${DDBB_USER}
    password: ${DDBB_PWD}
    schemas: SUPERHEROES_SCHEMA
    url: jdbc:h2:mem:superheroes
    locations: classpath:db.migration
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:superheroes
    driverClassName: org.h2.Driver
    username: ${DDBB_USER}
    password: ${DDBB_PWD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method